server {
    listen 80;

    server_name my-budgie.fr www.my-budgie.fr;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;

    server_name my-budgie.fr www.my-budgie.fr;

    ssl_certificate /etc/letsencrypt/live/my-budgie.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my-budgie.fr/privkey.pem;

    index index.php index.html;
    root /var/www/public;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}